### ISSUE TITLE
rtr_get_config_multiple() issue

### ISSUE THREAD

**Issue by jjr840430** [riboseinc/retrace#237]

**Comment by jjr840430** [comment]
infinite loop when using rtr_get_config_multiple()

The example code:
while (1) {
 r = rtr_get_config_multiple(...);
 if (r == 0)
   break;
 else
   do_something;                 /* not break from while statement */
}

**Comment by riataman** [comment]
this happens when where's no option after the one you are getting. as a quick work around you can add another option at the end of the file.

**Comment by riataman** [comment]
Fixed by https://github.com/riboseinc/retrace/pull/239

now initialize it like this:

RTR_CONFIG_HANDLE config = RTR_CONFIG_START;

**Comment by drystone** [comment]
I added this test to test/config.c and it fails
```
        ch = RTR_CONFIG_START;
        i = 0;
        do { 
                r = rtr_get_config_multiple(&ch, "config-test2", ARGUMENT_TYPE_STRING, ARGUMENT_TYPE_INT,
                    ARGUMENT_TYPE_END, &s, &i);
                ++i;
                assert(i < 10);
        } while (r);
```

**Comment by jjr840430** [comment]
@drystone I think the testing code should be as the followings:
```
        ch = RTR_CONFIG_START;
        i = 0;
        do {
        	int j;

                r = rtr_get_config_multiple(&ch, "config-test2", ARGUMENT_TYPE_STRING,  ARGUMENT_TYPE_INT,
                    ARGUMENT_TYPE_END, &s, &j);

                ++i;
                assert(i < 10);
        } while (r && ch != NULL);

```

**Comment by drystone** [comment]
@jjr840430 that's a good spot :) But it still breaks - I'll look at your latest PR

**Comment by jjr840430** [comment]
@drystone Still not working. I think the testing code for config isn't enough to test that function.

**Comment by drystone** [comment]
@jjr840430 so what's happening - is this Mac specific or more general?

**Comment by jjr840430** [comment]
@drystone It's Mac specific issue.
